/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 internet.gltf --transform
Author: salvey (https://sketchfab.com/salvey)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/increasing-internet-censorship-b7d1a1395690467abd133b682046e5d9
Title: Increasing Internet Censorship
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/internet-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, -22.7, -418.6]} rotation={[3.14, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Main_Layer_netherlands_0.geometry} material={materials.netherlands} />
          <mesh geometry={nodes.Main_Layer_peru_0.geometry} material={materials.peru} />
          <mesh geometry={nodes.Main_Layer_costa_rica_0.geometry} material={materials.costa_rica} />
          <mesh geometry={nodes.Main_Layer_argentina_0.geometry} material={materials.argentina} />
          <mesh geometry={nodes.Main_Layer_slovenia_0.geometry} material={materials.slovenia} />
          <mesh geometry={nodes.Main_Layer_taiwan_0.geometry} material={materials.slovenia} />
          <mesh geometry={nodes.Main_Layer_italy_0.geometry} material={materials.italy} />
          <mesh geometry={nodes.Main_Layer_belgium_0.geometry} material={materials.belgium} />
          <mesh geometry={nodes.Main_Layer_belize_0.geometry} material={materials.argentina} />
          <mesh geometry={nodes.Main_Layer_south_korea_0.geometry} material={materials.south_korea} />
          <mesh geometry={nodes.Main_Layer_brazil_0.geometry} material={materials.brazil} />
          <mesh geometry={nodes.Main_Layer_estonia_0.geometry} material={materials.brazil} />
          <mesh geometry={nodes.Main_Layer_denmark_0.geometry} material={materials.brazil} />
          <mesh geometry={nodes.Main_Layer_portugal_0.geometry} material={materials.portugal} />
          <mesh geometry={nodes.Main_Layer_latvia_0.geometry} material={materials.brazil} />
          <mesh geometry={nodes.Main_Layer_iceland_0.geometry} material={materials.brazil} />
          <mesh geometry={nodes.Main_Layer_new_zealand_0.geometry} material={materials.new_zealand} />
          <mesh geometry={nodes.Main_Layer_slovakia_0.geometry} material={materials.brazil} />
          <mesh geometry={nodes.Main_Layer_barbados_0.geometry} material={materials.brazil} />
          <mesh geometry={nodes.Main_Layer_austria_0.geometry} material={materials.brazil} />
          <mesh geometry={nodes.Main_Layer_ireland_0.geometry} material={materials.brazil} />
          <mesh geometry={nodes.Main_Layer_bulgaria_0.geometry} material={materials.brazil} />
          <mesh geometry={nodes.Main_Layer_guyana_0.geometry} material={materials.brazil} />
          <mesh geometry={nodes.Main_Layer_luxenbourg_0.geometry} material={materials.brazil} />
          <mesh geometry={nodes.Main_Layer_norway_0.geometry} material={materials.brazil} />
          <mesh geometry={nodes.Main_Layer_france_0.geometry} material={materials.brazil} />
          <mesh geometry={nodes.Main_Layer_croatia_0.geometry} material={materials.brazil} />
          <mesh geometry={nodes.Main_Layer_tunisia_0.geometry} material={materials.slovenia} />
          <mesh geometry={nodes.Main_Layer_jamaica_0.geometry} material={materials.slovenia} />
          <mesh geometry={nodes.Main_Layer_sweden_0.geometry} material={materials.slovenia} />
          <mesh geometry={nodes.Main_Layer_liechtenstein__0.geometry} material={materials.slovenia} />
          <mesh geometry={nodes.Main_Layer_cabo_verde_0.geometry} material={materials.new_zealand} />
          <mesh geometry={nodes.Main_Layer_spain_0.geometry} material={materials.slovenia} />
          <mesh geometry={nodes.Main_Layer_mauritius_0.geometry} material={materials.slovenia} />
          <mesh geometry={nodes.Main_Layer_namibia_0.geometry} material={materials.slovenia} />
          <mesh geometry={nodes.Main_Layer_germany_0.geometry} material={materials.slovenia} />
          <mesh geometry={nodes.Main_Layer_dominica_0.geometry} material={materials.brazil} />
          <mesh geometry={nodes.Main_Layer_switzerland_0.geometry} material={materials.switzerland} />
          <mesh geometry={nodes.Main_Layer_South_Africa_0.geometry} material={materials.South_Africa} />
          <mesh geometry={nodes.Main_Layer_USA_0.geometry} material={materials.argentina} />
          <mesh geometry={nodes.Main_Layer_chile_0.geometry} material={materials.slovenia} />
          <mesh geometry={nodes.Main_Layer_panama_0.geometry} material={materials.slovenia} />
          <mesh geometry={nodes.Main_Layer_canada_0.geometry} material={materials.slovenia} />
          <mesh geometry={nodes.Main_Layer_india_0.geometry} material={materials.slovenia} />
          <mesh geometry={nodes.Main_Layer_poland_0.geometry} material={materials.poland} />
          <mesh geometry={nodes.Main_Layer_uk_0.geometry} material={materials.material} />
          <mesh geometry={nodes.Main_Layer_st_kitts_and_nevis_0.geometry} material={materials.st_kitts_and_nevis} />
          <mesh geometry={nodes.Main_Layer_yellow_0.geometry} material={materials.yellow} />
          <mesh geometry={nodes.Main_Layer_green_0.geometry} material={materials.green} />
          <mesh geometry={nodes.Main_Layer_red_0.geometry} material={materials.material_49} />
          <mesh geometry={nodes['Main_Layer_Color_1-material_0'].geometry} material={materials['Color_1-material']} />
          <mesh geometry={nodes['Main_Layer_Color_2-material_0'].geometry} material={materials['Color_2-material']} />
          <mesh geometry={nodes['Main_Layer_Color_3-material_0'].geometry} material={materials['Color_3-material']} />
          <mesh geometry={nodes['Main_Layer_Color_4-material_0'].geometry} material={materials['Color_4-material']} />
          <mesh geometry={nodes['Main_Layer_Color5-material_0'].geometry} material={materials['Color5-material']} />
          <mesh geometry={nodes.Main_Layer_white_text_0.geometry} material={materials.white_text} />
          <mesh geometry={nodes.Main_Layer_white_text_0_1.geometry} material={materials.white_text} />
          <mesh geometry={nodes.Main_Layer_dark_letters_0.geometry} material={materials.dark_letters} />
          <mesh geometry={nodes.Main_Layer_Default_0.geometry} material={materials.Default} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/internet-transformed.glb')
